"""Train/val prompt datasets for SFT and GRPO training.

Deterministic 60-train / 20-val split (`plan.md` §Task 3). Both splits are
generated by seeding `random_layouts.empty_episode` with fixed seed ranges,
so the same seed always yields the same layout. Val seeds never overlap train
seeds.
"""
from __future__ import annotations

from dataclasses import dataclass

from harness.prompt_builder import build_user_message
from mini_factorio.layout import Layout
from mini_factorio.random_layouts import empty_episode


# Fixed seed ranges. Train and val are disjoint by construction.
TRAIN_SEEDS = list(range(0, 60))          # 60 layouts
VAL_SEEDS   = list(range(1000, 1020))     # 20 layouts (deliberately gapped to
                                           # avoid any temptation to merge later)


@dataclass
class Sample:
    seed: int
    layout: Layout
    prompt: str

    def to_dict(self) -> dict[str, str]:
        return {"seed": self.seed, "prompt": self.prompt}


def _sample_from_seed(seed: int) -> Sample:
    lay = empty_episode(seed=seed)
    return Sample(seed=seed, layout=lay, prompt=build_user_message(lay))


def train_samples() -> list[Sample]:
    return [_sample_from_seed(s) for s in TRAIN_SEEDS]


def val_samples() -> list[Sample]:
    return [_sample_from_seed(s) for s in VAL_SEEDS]


def as_hf_dataset(samples: list[Sample]):
    """Return a datasets.Dataset with columns {seed, prompt}. Import is lazy
    so `training.data` remains importable without the `datasets` library."""
    from datasets import Dataset  # type: ignore
    return Dataset.from_list([s.to_dict() for s in samples])
