"""Generated by mini_factorio/import_recipes.py — DO NOT EDIT.

Source: factoriolab data.json, Factorio version 2.0.77.
Machine footprints, crafting speeds and construction costs from factoriolab.
INSERTER_THROUGHPUT is a documented plan simplification (see plan.md §Simulator).
"""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class MachineDef:
    id: str
    size: tuple[int, int]  # (width, height) in tiles
    crafting_speed: float
    cost: dict[str, int]  # construction cost (items → count)
    fuel_category: str | None  # 'chemical' for burner, None otherwise
    usage_kw: float  # electrical or fuel power draw while active


@dataclass(frozen=True)
class PlaceableDef:
    id: str
    cost_per_place: dict[str, float]


MACHINES: dict[str, MachineDef] = {
    'electric-mining-drill': MachineDef(id='electric-mining-drill', size=(3, 3), crafting_speed=0.5, cost={'electronic-circuit': 3, 'iron-gear-wheel': 5, 'iron-plate': 10}, fuel_category=None, usage_kw=90.0),
    'stone-furnace': MachineDef(id='stone-furnace', size=(2, 2), crafting_speed=1.0, cost={'stone': 5}, fuel_category='chemical', usage_kw=90.0),
    'assembling-machine-1': MachineDef(id='assembling-machine-1', size=(3, 3), crafting_speed=0.5, cost={'electronic-circuit': 3, 'iron-gear-wheel': 5, 'iron-plate': 9}, fuel_category=None, usage_kw=75.0),
}

PLACEABLES: dict[str, PlaceableDef] = {
    'transport-belt': PlaceableDef(id='transport-belt', cost_per_place={'iron-plate': 0.5, 'iron-gear-wheel': 0.5}),
    'inserter': PlaceableDef(id='inserter', cost_per_place={'electronic-circuit': 1.0, 'iron-gear-wheel': 1.0, 'iron-plate': 1.0}),
}

BELT_SPEED = 15.0  # items/sec, yellow belt full throughput
INSERTER_THROUGHPUT = 0.83  # items/sec, basic inserter
COAL_ENERGY_MJ = 4.0  # MJ per coal unit

# Resource types available as ore patches on the map.
RESOURCE_TYPES: tuple[str, ...] = ('iron-ore', 'copper-ore', 'coal', 'stone')

# Facing directions for entities and belt tiles.
DIRECTIONS: tuple[str, ...] = ('north', 'east', 'south', 'west')

