"""Generate recipes.py and entities.py from factoriolab_data.json.

Run once from repo root:
    python -m mini_factorio.import_recipes

Emits real Factorio numbers (Factorio 2.0.77 dataset, MIT-licensed factoriolab). All
recipe times, machine sizes, crafting speeds, and construction costs come directly
from the JSON — nothing is written from memory. Plan §Data sources.
"""
from __future__ import annotations

import json
from fractions import Fraction
from pathlib import Path
from textwrap import dedent

DATA_FILE = Path(__file__).parent / "data" / "factoriolab_data.json"
RECIPES_OUT = Path(__file__).parent / "recipes.py"
ENTITIES_OUT = Path(__file__).parent / "entities.py"

# Recipes we care about for the green-science chain (green science = logistic-science-pack).
RECIPE_IDS = [
    # Mining
    "iron-ore",
    "copper-ore",
    "coal",
    "stone",
    # Smelting (in stone-furnace, consumes coal fuel)
    "iron-plate",
    "copper-plate",
    # Assembling
    "iron-gear-wheel",
    "copper-cable",
    "electronic-circuit",
    "transport-belt",
    "inserter",
    "logistic-science-pack",  # green science pack
]

# Machine entity ids (the buildable machines).
MACHINE_IDS = [
    "electric-mining-drill",
    "stone-furnace",
    "assembling-machine-1",
]

# Non-machine placeable entities (belt tile, inserter). These have costs but no
# crafting behaviour — they exist as first-class grid entities per plan.md line 28.
PLACEABLE_ITEM_IDS = [
    "transport-belt",
    "inserter",
]

# Producer-category mapping: which of our machine ids can run which recipes.
# Derived from the "producers" field on each recipe.
PRODUCER_TO_MACHINE_KIND = {
    "electric-mining-drill": "miner",
    "burner-mining-drill": "miner",  # ignored — we only expose electric
    "stone-furnace": "furnace",
    "steel-furnace": "furnace",
    "electric-furnace": "furnace",
    "assembling-machine-1": "assembler",
    "assembling-machine-2": "assembler",
    "assembling-machine-3": "assembler",
}


def _num(x) -> float:
    """Coerce factoriolab's numeric-or-fraction strings (e.g. '2160/7') to float."""
    if isinstance(x, (int, float)):
        return float(x)
    if isinstance(x, str) and "/" in x:
        return float(Fraction(x))
    return float(x)


def _find_recipe(recipes: list[dict], rid: str) -> dict:
    for r in recipes:
        if r.get("id") == rid:
            return r
    raise KeyError(f"recipe not found: {rid}")


def _find_item(items: list[dict], iid: str) -> dict:
    for it in items:
        if it.get("id") == iid:
            return it
    raise KeyError(f"item not found: {iid}")


def _kind_for_recipe(recipe: dict) -> str:
    """Which of our simulator machine kinds runs this recipe."""
    producers = recipe.get("producers", [])
    if "mining" in recipe.get("flags", []):
        return "miner"
    for p in producers:
        kind = PRODUCER_TO_MACHINE_KIND.get(p)
        if kind == "furnace":
            return "furnace"
        if kind == "assembler":
            return "assembler"
    raise ValueError(f"cannot classify recipe {recipe.get('id')}")


def build_recipes_py(data: dict, version: str) -> str:
    recipes = data["recipes"]
    lines = [
        '"""Generated by mini_factorio/import_recipes.py — DO NOT EDIT.',
        "",
        f"Source: factoriolab data.json, Factorio version {version}.",
        'Fields: `time` in seconds at crafting_speed=1.0. `in` = ingredients per craft.',
        '`out` = products per craft. `kind` = which machine kind runs it.',
        '"""',
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass, field",
        "",
        "",
        "@dataclass(frozen=True)",
        "class RecipeDef:",
        "    id: str",
        "    time: float",
        "    ingredients: dict[str, int]",
        "    products: dict[str, int]",
        "    kind: str  # 'miner' | 'furnace' | 'assembler'",
        "",
        "",
        "RECIPES: dict[str, RecipeDef] = {",
    ]
    for rid in RECIPE_IDS:
        r = _find_recipe(recipes, rid)
        kind = _kind_for_recipe(r)
        lines.append(
            f"    {rid!r}: RecipeDef("
            f"id={rid!r}, time={float(r['time'])!r}, "
            f"ingredients={dict(r.get('in', {}))!r}, "
            f"products={dict(r.get('out', {}))!r}, "
            f"kind={kind!r}),"
        )
    lines.append("}")
    lines.append("")
    lines.append("GREEN_SCIENCE_ITEM = 'logistic-science-pack'")
    lines.append("")
    return "\n".join(lines) + "\n"


def build_entities_py(data: dict, version: str) -> str:
    items = data["items"]
    recipes = data["recipes"]

    # Machine specs
    machine_specs: dict[str, dict] = {}
    for mid in MACHINE_IDS:
        it = _find_item(items, mid)
        m = it["machine"]
        # Construction cost is the recipe that produces this machine.
        recipe = _find_recipe(recipes, mid)
        cost = dict(recipe.get("in", {}))
        fuel = None
        if m.get("type") == "burner":
            fuel = m.get("fuelCategories", ["chemical"])[0]
        machine_specs[mid] = {
            "size": tuple(m["size"]),
            "crafting_speed": float(m["speed"]),
            "cost": cost,
            "fuel_category": fuel,
            "usage_kw": float(m.get("usage", 0)),
        }

    # Placeable-item specs (belt, inserter)
    placeable_specs: dict[str, dict] = {}
    for pid in PLACEABLE_ITEM_IDS:
        it = _find_item(items, pid)
        recipe = _find_recipe(recipes, pid)
        placeable_specs[pid] = {
            "cost_per_place": {k: v / _num(recipe["out"].get(pid, 1))
                               for k, v in recipe.get("in", {}).items()},
        }

    # Global constants
    belt_speed = float(_find_item(items, "transport-belt")["belt"]["speed"])

    # Inserter throughput: factoriolab stores a game-internal rotation-speed field
    # ("2160/7") not directly interpretable as items/sec without more of the item-swing
    # model. Plan §Simulator line 246 pins basic inserter throughput at 0.83 items/sec
    # (the widely-cited vanilla yellow-inserter figure). Documented simplification.
    inserter_throughput = 0.83

    # Coal fuel energy value (MJ per unit).
    coal_energy = float(_find_item(items, "coal")["fuel"]["value"])

    lines = [
        '"""Generated by mini_factorio/import_recipes.py — DO NOT EDIT.',
        "",
        f"Source: factoriolab data.json, Factorio version {version}.",
        'Machine footprints, crafting speeds and construction costs from factoriolab.',
        'INSERTER_THROUGHPUT is a documented plan simplification (see plan.md §Simulator).',
        '"""',
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "",
        "",
        "@dataclass(frozen=True)",
        "class MachineDef:",
        "    id: str",
        "    size: tuple[int, int]  # (width, height) in tiles",
        "    crafting_speed: float",
        "    cost: dict[str, int]  # construction cost (items → count)",
        "    fuel_category: str | None  # 'chemical' for burner, None otherwise",
        "    usage_kw: float  # electrical or fuel power draw while active",
        "",
        "",
        "@dataclass(frozen=True)",
        "class PlaceableDef:",
        "    id: str",
        "    cost_per_place: dict[str, float]",
        "",
        "",
        "MACHINES: dict[str, MachineDef] = {",
    ]
    for mid, s in machine_specs.items():
        lines.append(
            f"    {mid!r}: MachineDef("
            f"id={mid!r}, size={s['size']!r}, "
            f"crafting_speed={s['crafting_speed']!r}, "
            f"cost={s['cost']!r}, "
            f"fuel_category={s['fuel_category']!r}, "
            f"usage_kw={s['usage_kw']!r}),"
        )
    lines.append("}")
    lines.append("")
    lines.append("PLACEABLES: dict[str, PlaceableDef] = {")
    for pid, s in placeable_specs.items():
        lines.append(
            f"    {pid!r}: PlaceableDef("
            f"id={pid!r}, cost_per_place={s['cost_per_place']!r}),"
        )
    lines.append("}")
    lines.append("")
    lines.append(f"BELT_SPEED = {belt_speed!r}  # items/sec, yellow belt full throughput")
    lines.append(f"INSERTER_THROUGHPUT = {inserter_throughput!r}  # items/sec, basic inserter")
    lines.append(f"COAL_ENERGY_MJ = {coal_energy!r}  # MJ per coal unit")
    lines.append("")
    lines.append("# Resource types available as ore patches on the map.")
    lines.append("RESOURCE_TYPES: tuple[str, ...] = ('iron-ore', 'copper-ore', 'coal', 'stone')")
    lines.append("")
    lines.append("# Facing directions for entities and belt tiles.")
    lines.append("DIRECTIONS: tuple[str, ...] = ('north', 'east', 'south', 'west')")
    lines.append("")
    return "\n".join(lines) + "\n"


def main() -> None:
    data = json.loads(DATA_FILE.read_text())
    version = data.get("version", {}).get("base", "unknown")
    if isinstance(version, dict):
        version = str(version)
    RECIPES_OUT.write_text(build_recipes_py(data, str(version)))
    ENTITIES_OUT.write_text(build_entities_py(data, str(version)))
    print(f"Wrote {RECIPES_OUT}")
    print(f"Wrote {ENTITIES_OUT}")


if __name__ == "__main__":
    main()
