"""Generated by mini_factorio/import_recipes.py — DO NOT EDIT.

Source: factoriolab data.json, Factorio version 2.0.77.
Fields: `time` in seconds at crafting_speed=1.0. `in` = ingredients per craft.
`out` = products per craft. `kind` = which machine kind runs it.
"""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class RecipeDef:
    id: str
    time: float
    ingredients: dict[str, int]
    products: dict[str, int]
    kind: str  # 'miner' | 'furnace' | 'assembler'


RECIPES: dict[str, RecipeDef] = {
    'iron-ore': RecipeDef(id='iron-ore', time=1.0, ingredients={}, products={'iron-ore': 1}, kind='miner'),
    'copper-ore': RecipeDef(id='copper-ore', time=1.0, ingredients={}, products={'copper-ore': 1}, kind='miner'),
    'coal': RecipeDef(id='coal', time=1.0, ingredients={}, products={'coal': 1}, kind='miner'),
    'stone': RecipeDef(id='stone', time=1.0, ingredients={}, products={'stone': 1}, kind='miner'),
    'iron-plate': RecipeDef(id='iron-plate', time=3.2, ingredients={'iron-ore': 1}, products={'iron-plate': 1}, kind='furnace'),
    'copper-plate': RecipeDef(id='copper-plate', time=3.2, ingredients={'copper-ore': 1}, products={'copper-plate': 1}, kind='furnace'),
    'iron-gear-wheel': RecipeDef(id='iron-gear-wheel', time=0.5, ingredients={'iron-plate': 2}, products={'iron-gear-wheel': 1}, kind='assembler'),
    'copper-cable': RecipeDef(id='copper-cable', time=0.5, ingredients={'copper-plate': 1}, products={'copper-cable': 2}, kind='assembler'),
    'electronic-circuit': RecipeDef(id='electronic-circuit', time=0.5, ingredients={'iron-plate': 1, 'copper-cable': 3}, products={'electronic-circuit': 1}, kind='assembler'),
    'transport-belt': RecipeDef(id='transport-belt', time=0.5, ingredients={'iron-plate': 1, 'iron-gear-wheel': 1}, products={'transport-belt': 2}, kind='assembler'),
    'inserter': RecipeDef(id='inserter', time=0.5, ingredients={'electronic-circuit': 1, 'iron-gear-wheel': 1, 'iron-plate': 1}, products={'inserter': 1}, kind='assembler'),
    'logistic-science-pack': RecipeDef(id='logistic-science-pack', time=6.0, ingredients={'inserter': 1, 'transport-belt': 1}, products={'logistic-science-pack': 1}, kind='assembler'),
}

GREEN_SCIENCE_ITEM = 'logistic-science-pack'

